### ISSUE TITLE
nlg.py error

### ISSUE THREAD

**Issue by Hongze-Wang** [MiuLab/D3Q#1]
Hi,

Sorry to interrupt, but I encounter an error when reproduce your work.

The original code in nlg.py

    def load_nlg_model(self, model_path):
        """ load the trained NLG model """
        
        model_params = pickle.load(open(model_path, 'rb'))
    
        hidden_size = model_params['model']['Wd'].shape[0]
        output_size = model_params['model']['Wd'].shape[1]

will encounter the error that:

building user simulator model
Traceback (most recent call last):
  File "run.py", line 244, in <module>
    nlg_model.load_nlg_model(nlg_model_path)
  File "C:\Users\wangh\D3Q-master\D3Q\src\deep_dialog\nlg\nlg.py", line 138, in load_nlg_model
    model_params = pickle.load(open(model_path)) # , 'rb'), encoding='bytes')
TypeError: a bytes-like object is required, not 'str'

So I change that to:
    def load_nlg_model(self, model_path):
        """ load the trained NLG model """
        
        model_params = pickle.load(open(model_path, 'rb'), encoding='bytes')
    
        hidden_size = model_params['model']['Wd'].shape[0]
        output_size = model_params['model']['Wd'].shape[1]

then I will encounter the following error:

building user simulator model
Traceback (most recent call last):
  File "run.py", line 244, in <module>
    nlg_model.load_nlg_model(nlg_model_path)
  File "C:\Users\wangh\D3Q-master\D3Q\src\deep_dialog\nlg\nlg.py", line 140, in load_nlg_model
    hidden_size = model_params['model']['Wd'].shape[0]
KeyError: 'model'

Which means that the model stored in nlg_model_path has no index 'model'

Could please help me with that ？

Thanks
Steve Wang

**Comment by Hongze-Wang** [comment]
Sorry,I should run on Linux.
